from django.urls import path, include

#from . import views
from trelloapp.views import (Dash,
                             BoardCreateView,
                             BoardView,
                             ListOfBoards,
                             BoardDetailView,
                             EditBoard,
                             DeleteBoard,
                             EditList,
                             MyAjaxView,
                             ListView,
                             CardCreateView,
                             CardList,
                             UpdateListView,
                             UpdateCardView,
                             CreateCardView,
                             BoardEdit,
                             BoardViewTrelloBase,
                             BoardCreate,
                             BoardViewTrelloBase,
                             ListCreate,
                             DragCard,
                             CardView,
                             CardTitleUpdate,
                             CardLabelUpdate,
                             DragCard,
                             InviteMember,
                             Email,
                             LoginInvite,
                             ArchiveList,
                             ListSetting,
                             ArchiveBoard,
                             ArchiveCard,
                             RetrieveBoard,
                             RetrieveList,
                             DeleteArchivedList,
                             RetrieveCard,
                             DeleteCard,
                             LeaveBoard,
                             InvitedBoard,
                            )

urlpatterns = [
    path('', Dash.as_view(), name='dashboard'),

    path('boards/lists/',BoardViewTrelloBase.as_view(), name='boardslist'),
    
    path('sample-ajax/', MyAjaxView.as_view(), name='dashboards'),
    path('board/create/', BoardCreateView.as_view(), name='createboard'),
    path('board/detail/<int:board_id>/', BoardView.as_view(), name='board'),
    path('boards/',ListOfBoards.as_view(), name='listofboards'),
    path('board/<int:pk>/',BoardDetailView.as_view(),name='detail'),
    path('board/edit/<int:board_id>/',EditBoard.as_view(), name='editboard'),
    path('board/delete/<int:board_id>/',DeleteBoard.as_view(),name='deleteboard' ),
    path('board/<board_id>/list/edit/<int:pk>/', EditList.as_view(), name = 'editlist'),
    path('board/<int:pk>/lists/',ListView.as_view(), name='listviews'),
    path('board/<int:pk>/list/<int:list_id>/create/card/', CardCreateView.as_view(), name='addcard'),
    path('board/<int:board_id>/list/<int:list_id>/cards/',CardList.as_view(), name='cardviews'),
    path('board/<int:board_id>/list/<int:list_id>/update/',UpdateListView.as_view(), name='list_update'),
    path('board/<int:board_id>/list/<int:list_id>/card/<int:card_id>/update/',UpdateCardView.as_view(), name='card_update'),
    path('board/<int:board_id>/list/<int:list_id>/card/added/',CreateCardView.as_view(), name='create_card'),
    path('board/edit/<int:board_id>/edited/',BoardEdit.as_view(), name='edit_board'),
    path('board/created/', BoardCreate.as_view(), name='boardcreate'),
    path('boards/lists/',BoardViewTrelloBase.as_view(), name='boardslist'),
    path('board/<int:pk>/list/',ListCreate.as_view(), name='list_views'), 
    path('board/<int:board_id>/list/<int:list_id>/card/<int:card_id>/',CardView.as_view(), name='card_views'),
    path('board/<int:board_id>/list/<int:list_id>/card/<int:card_id>/update/title/',CardTitleUpdate.as_view(), name='update_card'),
    path('board/<int:board_id>/list/<int:list_id>/card/<int:card_id>/update/label/',CardLabelUpdate.as_view(), name='update_label'),
    path('board/<int:board_id>/list/<int:list_id>/card/<int:card_id>/dragged/card/',DragCard.as_view(), name='card_drag'),
    path('board/<int:board_id>/invite/',InviteMember.as_view(),name='invitememberform'),
    #path('invitation/sent/',views.email, name = 'sent')
    path('board/<int:board_id>/invitation/',Email.as_view(), name = 'sent'),
    path('boards/list/',ListOfBoards.as_view(), name='invited'),
    path('board/<int:board_id>/invitation/(?P<uid>[0-9A-Za-z_\-]+)/login/', LoginInvite.as_view(),name='logininvitation'),
    path('archived/board/<int:board_id>/lists/<int:list_id>/', ArchiveList.as_view(), name='archive_list'),
    path('Setting/board/<int:board_id>/list/<int:list_id>/', ListSetting.as_view(), name='list_view_setting'),
    path('archive/board/<int:board_id>', ArchiveBoard.as_view(), name='archive_board'),
    path('archive/board/<int:board_id>/list/<int:list_id>/card/<int:card_id>/',ArchiveCard.as_view(), name='archive_card' ),
    path('retrieve/board/<int:board_id>/', RetrieveBoard.as_view(), name='retrieve_board'),
    path('archived/board/<int:board_id>/list/<int:list_id>/', RetrieveList.as_view(), name='retrieve_list'),
    path('board/<int:board_id>/list/<int:list_id>/deleted/', DeleteArchivedList.as_view(), name='delete_archived_list'),
    path('Retrieve/board/<int:board_id>/list/<int:list_id>/card/<int:card_id>/', RetrieveCard.as_view(), name='retrieve_card'),
    path('Delete/board/<int:board_id>/list/<int:list_id>/card/<int:card_id>/', DeleteCard.as_view(), name='delete_card'),
    path('leave/board/<int:board_id>/', LeaveBoard.as_view(), name='leave_board'),
    path('invited/board/<int:board_id>/', InvitedBoard.as_view(), name='invited'),

]