# Generated by Django 2.2.4 on 2019-09-24 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardinvite',
            name='sender',
        ),
        migrations.AlterField(
            model_name='board',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 24, 9, 42, 9, 647814, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 24, 9, 42, 9, 648456, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trellolist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 24, 9, 42, 9, 648140, tzinfo=utc)),
        ),
    ]
