# Generated by Django 2.2.4 on 2019-09-25 11:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0003_auto_20190925_0754'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='board',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trellolist',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 11, 13, 33, 889737, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 11, 13, 33, 890415, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trellolist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 11, 13, 33, 890084, tzinfo=utc)),
        ),
    ]
