# Generated by Django 2.2.4 on 2019-10-02 09:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0006_auto_20191002_0838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Draggedcard',
        ),
        migrations.AlterField(
            model_name='board',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 9, 24, 7, 528151, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 9, 24, 7, 529263, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trellolist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 9, 24, 7, 528487, tzinfo=utc)),
        ),
    ]
