# Generated by Django 2.2.4 on 2019-10-02 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0007_auto_20191002_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('M', 'MOVED'), ('R', 'RENAME'), ('dragged', 'dragged')], max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 14, 44, 25, 159932, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 14, 44, 25, 161045, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trellolist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 14, 44, 25, 160270, tzinfo=utc)),
        ),
    ]
