# Generated by Django 2.2.4 on 2019-10-04 08:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0008_auto_20191002_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('M', 'MOVED'), ('R', 'RENAME'), ('dragged', 'dragged'), ('from', 'from'), ('to', 'to')], max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 4, 8, 20, 58, 545427, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 4, 8, 20, 58, 546957, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trellolist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 4, 8, 20, 58, 546520, tzinfo=utc)),
        ),
    ]
